#!/bin/sh

#If you have access to git:

#Installation:
	git clone https://github.com/Jesin/dotvim.git ~/.vim

#Get the vimrc files in the right place:
	cd ~/.vim
	for x in vimrc gvimrc; do
		if [ -e "~/.$x" ]; then
			echo "runtime $x" | diff -q "~/.$x" - || exit "$?"
		else
			echo "runtime $x" > "~/.$x" || exit "$?"
		fi
	done


# Install and update plugins:
	vim '+BundleInstall!' '+qa'


#NOTE FOR SVN:
	#If you want 'svn co' to produce a directory structure that is
	#immediately usable in the way it would be after a 'git clone',
	#then append /trunk to the URL of the git repository.
